### ISSUE TITLE
Missing underscore.js import (probably)

### ISSUE THREAD

**Issue by dimascrocco** [colintoh/sails-hook-pagify#3]
Hallo, I'm using Sails 0.12.3 within the code below:

```
  Panda.pagify('pandas', {
    findQuery: {'name': {'like': '%foratemer%'}},
    sort: ['createdAt DESC'],
    page: 1
  }).then(function(data){
    
  }).catch(function(err){

  });
```

And it screams at me this:
```
 TypeError: Cannot read property 'defaults' of undefined
    at _getPage (.../server/node_modules/sails-hook-pagify/lib/pagify.js:22:20)
    at child.model.pagify (.../server/node_modules/sails-hook-pagify/lib/pagify.js:72:16)
```

I just added 

`var _ = require("underscore");
`

and it worked. I'm new to Sails and javascript (server side), so I am not sure if this is the right way of fixing this issue.

Thanx for this plugin.

**Comment by colintoh** [comment]
Did you disable lodash? Sails.js comes with lodash
